// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: subscale.proto
#ifndef GRPC_subscale_2eproto__INCLUDED
#define GRPC_subscale_2eproto__INCLUDED

#include "subscale.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace subscale {

class SubscaleRoutes final {
 public:
  static constexpr char const* service_full_name() {
    return "subscale.SubscaleRoutes";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::subscale::SubspaceTable* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::subscale::SubspaceTable>> AsyncRemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::subscale::SubspaceTable>>(AsyncRemoteSubscaleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::subscale::SubspaceTable>> PrepareAsyncRemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::subscale::SubspaceTable>>(PrepareAsyncRemoteSubscaleRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData* request, ::subscale::SubspaceTable* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData* request, ::subscale::SubspaceTable* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::subscale::SubspaceTable>* AsyncRemoteSubscaleRaw(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::subscale::SubspaceTable>* PrepareAsyncRemoteSubscaleRaw(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::subscale::SubspaceTable* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::subscale::SubspaceTable>> AsyncRemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::subscale::SubspaceTable>>(AsyncRemoteSubscaleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::subscale::SubspaceTable>> PrepareAsyncRemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::subscale::SubspaceTable>>(PrepareAsyncRemoteSubscaleRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData* request, ::subscale::SubspaceTable* response, std::function<void(::grpc::Status)>) override;
      void RemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData* request, ::subscale::SubspaceTable* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::subscale::SubspaceTable>* AsyncRemoteSubscaleRaw(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::subscale::SubspaceTable>* PrepareAsyncRemoteSubscaleRaw(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RemoteSubscale_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RemoteSubscale(::grpc::ServerContext* context, const ::subscale::SubscaleData* request, ::subscale::SubspaceTable* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RemoteSubscale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RemoteSubscale() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RemoteSubscale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteSubscale(::grpc::ServerContext* /*context*/, const ::subscale::SubscaleData* /*request*/, ::subscale::SubspaceTable* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemoteSubscale(::grpc::ServerContext* context, ::subscale::SubscaleData* request, ::grpc::ServerAsyncResponseWriter< ::subscale::SubspaceTable>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RemoteSubscale<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RemoteSubscale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RemoteSubscale() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::subscale::SubscaleData, ::subscale::SubspaceTable>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::subscale::SubscaleData* request, ::subscale::SubspaceTable* response) { return this->RemoteSubscale(context, request, response); }));}
    void SetMessageAllocatorFor_RemoteSubscale(
        ::grpc::MessageAllocator< ::subscale::SubscaleData, ::subscale::SubspaceTable>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::subscale::SubscaleData, ::subscale::SubspaceTable>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RemoteSubscale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteSubscale(::grpc::ServerContext* /*context*/, const ::subscale::SubscaleData* /*request*/, ::subscale::SubspaceTable* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RemoteSubscale(
      ::grpc::CallbackServerContext* /*context*/, const ::subscale::SubscaleData* /*request*/, ::subscale::SubspaceTable* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RemoteSubscale<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RemoteSubscale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RemoteSubscale() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RemoteSubscale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteSubscale(::grpc::ServerContext* /*context*/, const ::subscale::SubscaleData* /*request*/, ::subscale::SubspaceTable* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RemoteSubscale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RemoteSubscale() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RemoteSubscale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteSubscale(::grpc::ServerContext* /*context*/, const ::subscale::SubscaleData* /*request*/, ::subscale::SubspaceTable* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemoteSubscale(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RemoteSubscale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RemoteSubscale() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RemoteSubscale(context, request, response); }));
    }
    ~WithRawCallbackMethod_RemoteSubscale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteSubscale(::grpc::ServerContext* /*context*/, const ::subscale::SubscaleData* /*request*/, ::subscale::SubspaceTable* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RemoteSubscale(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RemoteSubscale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RemoteSubscale() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::subscale::SubscaleData, ::subscale::SubspaceTable>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::subscale::SubscaleData, ::subscale::SubspaceTable>* streamer) {
                       return this->StreamedRemoteSubscale(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RemoteSubscale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RemoteSubscale(::grpc::ServerContext* /*context*/, const ::subscale::SubscaleData* /*request*/, ::subscale::SubspaceTable* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRemoteSubscale(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::subscale::SubscaleData,::subscale::SubspaceTable>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RemoteSubscale<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RemoteSubscale<Service > StreamedService;
};

}  // namespace subscale


#endif  // GRPC_subscale_2eproto__INCLUDED
