// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: subscale.proto

#include "subscale.pb.h"
#include "subscale.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace subscale {

static const char* SubscaleRoutes_method_names[] = {
  "/subscale.SubscaleRoutes/RemoteSubscale",
};

std::unique_ptr< SubscaleRoutes::Stub> SubscaleRoutes::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SubscaleRoutes::Stub> stub(new SubscaleRoutes::Stub(channel, options));
  return stub;
}

SubscaleRoutes::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RemoteSubscale_(SubscaleRoutes_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SubscaleRoutes::Stub::RemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::subscale::SubspaceTable* response) {
  return ::grpc::internal::BlockingUnaryCall< ::subscale::SubscaleData, ::subscale::SubspaceTable, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RemoteSubscale_, context, request, response);
}

void SubscaleRoutes::Stub::async::RemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData* request, ::subscale::SubspaceTable* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::subscale::SubscaleData, ::subscale::SubspaceTable, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RemoteSubscale_, context, request, response, std::move(f));
}

void SubscaleRoutes::Stub::async::RemoteSubscale(::grpc::ClientContext* context, const ::subscale::SubscaleData* request, ::subscale::SubspaceTable* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RemoteSubscale_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::subscale::SubspaceTable>* SubscaleRoutes::Stub::PrepareAsyncRemoteSubscaleRaw(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::subscale::SubspaceTable, ::subscale::SubscaleData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RemoteSubscale_, context, request);
}

::grpc::ClientAsyncResponseReader< ::subscale::SubspaceTable>* SubscaleRoutes::Stub::AsyncRemoteSubscaleRaw(::grpc::ClientContext* context, const ::subscale::SubscaleData& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRemoteSubscaleRaw(context, request, cq);
  result->StartCall();
  return result;
}

SubscaleRoutes::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SubscaleRoutes_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SubscaleRoutes::Service, ::subscale::SubscaleData, ::subscale::SubspaceTable, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SubscaleRoutes::Service* service,
             ::grpc::ServerContext* ctx,
             const ::subscale::SubscaleData* req,
             ::subscale::SubspaceTable* resp) {
               return service->RemoteSubscale(ctx, req, resp);
             }, this)));
}

SubscaleRoutes::Service::~Service() {
}

::grpc::Status SubscaleRoutes::Service::RemoteSubscale(::grpc::ServerContext* context, const ::subscale::SubscaleData* request, ::subscale::SubspaceTable* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace subscale

